# Avaliação Baseline, Conteúdo e Colaborativo

Este notebook compara quatro variantes de recomendação:
- Baseline (popularidade/média por item)
- Conteúdo (categorias dos negócios com Jaccard)
- Colaborativo com similaridade cosseno
- Colaborativo com similaridade Jaccard (binária por itens interagidos)

A avaliação foi separada em dois blocos:
- Erro de rating: `RMSE`
- Qualidade de ranking no conjunto de teste por utilizador: `Precision@K`, `Recall@K`, `MAP@K`, `NDCG@K`

In [1]:
import json
import math
import os
import random
import time
from collections import Counter, defaultdict

import pandas as pd

## Carregamento de dados

In [2]:
def load_line_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                yield json.loads(line)


def load_reviews(path):
    user_item_latest = defaultdict(dict)

    for record in load_line_json(path):
        user_id = record.get("user_id")
        item_id = record.get("business_id")
        rating = record.get("stars")
        date_raw = record.get("date")

        if user_id is None or item_id is None or rating is None or date_raw is None:
            continue

        timestamp = pd.to_datetime(date_raw, errors="coerce")
        if pd.isna(timestamp):
            continue

        rating_value = float(rating)
        previous = user_item_latest[user_id].get(item_id)

        # Keep only the most recent interaction per (user, item) for temporal split.
        if previous is None or timestamp > previous[1]:
            user_item_latest[user_id][item_id] = (rating_value, timestamp)

    user_ratings = defaultdict(dict)
    user_item_events = defaultdict(list)

    for user_id, item_map in user_item_latest.items():
        for item_id, (rating_value, timestamp) in item_map.items():
            user_ratings[user_id][item_id] = rating_value
            user_item_events[user_id].append((item_id, rating_value, timestamp))

        user_item_events[user_id].sort(key=lambda event: event[2])

    return user_ratings, user_item_events


def load_business_categories(path):
    categories = {}
    for record in load_line_json(path):
        item_id = record.get("business_id")
        raw_categories = record.get("categories") or ""
        categories[item_id] = {
            part.strip().lower()
            for part in raw_categories.split(",")
            if part.strip()
        }
    return categories

## Preparação de treino e estatísticas

In [3]:
def split_train_test(user_ratings, min_ratings=5, test_ratio=0.2, min_test_items=2, seed=42):
    random.seed(seed)
    train = {}
    test = []

    required_ratings = max(min_ratings, min_test_items + 1)

    for user_id, ratings in user_ratings.items():
        if len(ratings) < required_ratings:
            train[user_id] = ratings.copy()
            continue

        items = list(ratings.items())
        n_test = max(min_test_items, int(len(items) * test_ratio))
        n_test = min(n_test, len(items) - 1)
        test_items = random.sample(items, n_test)
        test_map = {item: rating for item, rating in test_items}

        train[user_id] = {item: rating for item, rating in items if item not in test_map}
        for item, rating in test_items:
            test.append((user_id, item, rating))

    return train, test


def split_train_test_temporal(user_item_events, min_ratings=5, test_ratio=0.2, min_test_items=2):
    train = {}
    test = []

    required_ratings = max(min_ratings, min_test_items + 1)

    for user_id, events in user_item_events.items():
        if len(events) < required_ratings:
            train[user_id] = {item_id: rating for item_id, rating, _ in events}
            continue

        n_test = max(min_test_items, int(len(events) * test_ratio))
        n_test = min(n_test, len(events) - 1)

        train_events = events[:-n_test]
        test_events = events[-n_test:]

        train[user_id] = {item_id: rating for item_id, rating, _ in train_events}
        for item_id, rating, _ in test_events:
            test.append((user_id, item_id, rating))

    return train, test


def build_item_stats(train_user_ratings):
    item_counts = Counter()
    item_sum = Counter()

    for ratings in train_user_ratings.values():
        for item_id, rating in ratings.items():
            item_counts[item_id] += 1
            item_sum[item_id] += rating

    item_mean = {
        item_id: item_sum[item_id] / item_counts[item_id]
        for item_id in item_counts
    }
    global_mean = sum(item_sum.values()) / sum(item_counts.values()) if item_counts else 0.0

    return item_counts, item_mean, global_mean

In [4]:
def jaccard_similarity(a, b):
    if not a or not b:
        return 0.0
    inter = len(a & b)
    if inter == 0:
        return 0.0
    union = len(a | b)
    return inter / union


def build_user_profile_categories(user_id, train_user_ratings, categories):
    profile = set()
    for item_id in train_user_ratings.get(user_id, {}):
        profile |= categories.get(item_id, set())
    return profile


def compute_user_norms(train_user_ratings):
    return {
        user_id: math.sqrt(sum(rating * rating for rating in ratings.values()))
        for user_id, ratings in train_user_ratings.items()
    }


def cosine_similarity_ratings(user_ratings_a, user_ratings_b, norm_a, norm_b):
    if norm_a <= 0 or norm_b <= 0:
        return 0.0

    common = set(user_ratings_a).intersection(user_ratings_b)
    if not common:
        return 0.0

    dot = sum(user_ratings_a[item_id] * user_ratings_b[item_id] for item_id in common)
    return dot / (norm_a * norm_b)


def jaccard_similarity_user_items(user_ratings_a, user_ratings_b):
    items_a = set(user_ratings_a)
    items_b = set(user_ratings_b)
    if not items_a or not items_b:
        return 0.0
    inter = len(items_a & items_b)
    if inter == 0:
        return 0.0
    union = len(items_a | items_b)
    return inter / union


def build_collaborative_score_map_cosine(user_id, train_user_ratings, user_norms):
    target_ratings = train_user_ratings.get(user_id, {})
    if not target_ratings:
        return {}

    target_norm = user_norms.get(user_id, 0.0)
    if target_norm <= 0:
        return {}

    weighted_sum = defaultdict(float)
    weight_total = defaultdict(float)

    for other_user_id, other_ratings in train_user_ratings.items():
        if other_user_id == user_id:
            continue

        other_norm = user_norms.get(other_user_id, 0.0)
        sim = cosine_similarity_ratings(target_ratings, other_ratings, target_norm, other_norm)
        if sim <= 0:
            continue

        for item_id, rating in other_ratings.items():
            if item_id in target_ratings:
                continue
            weighted_sum[item_id] += sim * rating
            weight_total[item_id] += sim

    return {
        item_id: weighted_sum[item_id] / weight_total[item_id]
        for item_id in weighted_sum
        if weight_total[item_id] > 0
    }


def build_collaborative_score_map_jaccard(user_id, train_user_ratings):
    target_ratings = train_user_ratings.get(user_id, {})
    if not target_ratings:
        return {}

    weighted_sum = defaultdict(float)
    weight_total = defaultdict(float)

    for other_user_id, other_ratings in train_user_ratings.items():
        if other_user_id == user_id:
            continue

        sim = jaccard_similarity_user_items(target_ratings, other_ratings)
        if sim <= 0:
            continue

        for item_id, rating in other_ratings.items():
            if item_id in target_ratings:
                continue
            weighted_sum[item_id] += sim * rating
            weight_total[item_id] += sim

    return {
        item_id: weighted_sum[item_id] / weight_total[item_id]
        for item_id in weighted_sum
        if weight_total[item_id] > 0
    }


def predict_baseline_rating(item_id, item_mean, global_mean):
    return item_mean.get(item_id, global_mean)


def predict_content_rating(user_id, item_id, train_user_ratings, categories, global_mean):
    user_items = train_user_ratings.get(user_id, {})
    if not user_items:
        return global_mean

    target_cats = categories.get(item_id, set())
    weighted_sum = 0.0
    weight_total = 0.0

    for rated_item, rating in user_items.items():
        sim = jaccard_similarity(target_cats, categories.get(rated_item, set()))
        if sim > 0:
            weighted_sum += sim * rating
            weight_total += sim

    if weight_total > 0:
        return weighted_sum / weight_total

    user_mean = sum(user_items.values()) / len(user_items)
    return user_mean

## Métricas de ranking por utilizador (teste)

Fórmulas usadas, por utilizador $u$ e no top-$K$:

$$
Precision@K_u = \frac{|Rel_u \cap Rec_u(K)|}{K}
$$

$$
Recall@K_u = \frac{|Rel_u \cap Rec_u(K)|}{|Rel_u|}
$$

$$
AP@K_u = \frac{1}{\min(|Rel_u|, K)}\sum_{i=1}^{K} Precision@i_u \cdot rel_u(i)
$$

$$
DCG@K_u = \sum_{i=1}^{K} \frac{rel_u(i)}{\log_2(i+1)}, \quad
NDCG@K_u = \frac{DCG@K_u}{IDCG@K_u}
$$

Onde $rel_u(i)=1$ se o item na posição $i$ é relevante para o utilizador no conjunto de teste, senão $0$.

No final, as métricas de ranking são agregadas por média macro entre utilizadores para refletir também utilizadores com desempenho fraco.

In [5]:
def rank_baseline(user_id, train_user_ratings, candidates, item_mean, top_k):
    rated = set(train_user_ratings.get(user_id, {}))
    ranked = [item for item in candidates if item not in rated]
    return ranked[:top_k]


def rank_content(user_id, train_user_ratings, categories, all_items, top_k):
    rated = set(train_user_ratings.get(user_id, {}))
    profile = build_user_profile_categories(user_id, train_user_ratings, categories)

    scores = []
    for item_id in all_items:
        if item_id in rated:
            continue
        score = jaccard_similarity(profile, categories.get(item_id, set()))
        scores.append((score, item_id))

    scores.sort(key=lambda x: x[0], reverse=True)
    return [item for _, item in scores[:top_k]]


def rank_from_score_loader(user_id, top_k, score_loader):
    score_map = score_loader(user_id)
    ranked = sorted(score_map.items(), key=lambda item: item[1], reverse=True)
    return [item_id for item_id, _ in ranked[:top_k]]


def predict_from_score_loader(user_id, item_id, score_loader, user_means, global_mean):
    score_map = score_loader(user_id)
    if item_id in score_map:
        return score_map[item_id]
    return user_means.get(user_id, global_mean)

In [6]:
def evaluate_rmse(test_set, predictor, label="RMSE", progress_step=10):
    mse = 0.0
    count = 0
    total = len(test_set)

    if total == 0:
        print(f"{label}: 100% (no test data)")
        return 0.0

    next_progress = progress_step
    started_at = time.perf_counter()

    for index, (user_id, item_id, actual) in enumerate(test_set, start=1):
        pred = predictor(user_id, item_id)
        err = pred - actual
        mse += err * err
        count += 1

        progress = (index / total) * 100
        if progress >= next_progress or index == total:
            elapsed = time.perf_counter() - started_at
            print(f"{label}: {progress:.0f}% ({index}/{total}) - {elapsed:.1f}s")
            next_progress += progress_step

    return math.sqrt(mse / count) if count else 0.0


def build_test_relevance_by_user(test_set):
    relevance = defaultdict(set)
    for user_id, item_id, _ in test_set:
        relevance[user_id].add(item_id)
    return relevance


def precision_at_k_for_user(ranked_items, relevant_items, k):
    if k <= 0:
        return 0.0
    hits = sum(1 for item in ranked_items[:k] if item in relevant_items)
    return hits / k


def recall_at_k_for_user(ranked_items, relevant_items, k):
    if not relevant_items:
        return 0.0
    hits = sum(1 for item in ranked_items[:k] if item in relevant_items)
    return hits / len(relevant_items)


def average_precision_at_k_for_user(ranked_items, relevant_items, k):
    if not relevant_items or k <= 0:
        return 0.0

    hits = 0
    precision_sum = 0.0
    for index, item_id in enumerate(ranked_items[:k], start=1):
        if item_id in relevant_items:
            hits += 1
            precision_sum += hits / index

    denominator = min(len(relevant_items), k)
    return precision_sum / denominator if denominator else 0.0


def ndcg_at_k_for_user(ranked_items, relevant_items, k):
    if not relevant_items or k <= 0:
        return 0.0

    dcg = 0.0
    for index, item_id in enumerate(ranked_items[:k], start=1):
        rel = 1.0 if item_id in relevant_items else 0.0
        if rel > 0:
            dcg += rel / math.log2(index + 1)

    ideal_hits = min(len(relevant_items), k)
    if ideal_hits == 0:
        return 0.0

    idcg = sum(1.0 / math.log2(index + 1) for index in range(1, ideal_hits + 1))
    return dcg / idcg if idcg > 0 else 0.0


def evaluate_ranking_metrics_by_user(test_set, ranker, k, label="Ranking@K", progress_step=10):
    relevance_by_user = build_test_relevance_by_user(test_set)
    user_ids = list(relevance_by_user.keys())
    total_users = len(user_ids)

    if total_users == 0:
        print(f"{label}: 100% (no test users)")
        empty = pd.DataFrame(columns=["user_id", "precision", "recall", "map", "ndcg", "n_relevant_test"])
        return {
            "macro_precision": 0.0,
            "macro_recall": 0.0,
            "macro_map": 0.0,
            "macro_ndcg": 0.0,
            "users_evaluated": 0,
            "per_user": empty,
        }

    rows = []
    next_progress = progress_step
    started_at = time.perf_counter()

    for index, user_id in enumerate(user_ids, start=1):
        relevant_items = relevance_by_user[user_id]
        ranked_items = ranker(user_id, k)

        precision_u = precision_at_k_for_user(ranked_items, relevant_items, k)
        recall_u = recall_at_k_for_user(ranked_items, relevant_items, k)
        map_u = average_precision_at_k_for_user(ranked_items, relevant_items, k)
        ndcg_u = ndcg_at_k_for_user(ranked_items, relevant_items, k)

        rows.append(
            {
                "user_id": user_id,
                "precision": precision_u,
                "recall": recall_u,
                "map": map_u,
                "ndcg": ndcg_u,
                "n_relevant_test": len(relevant_items),
            }
        )

        progress = (index / total_users) * 100
        if progress >= next_progress or index == total_users:
            elapsed = time.perf_counter() - started_at
            print(f"{label}: {progress:.0f}% ({index}/{total_users}) - {elapsed:.1f}s")
            next_progress += progress_step

    per_user_df = pd.DataFrame(rows)

    return {
        "macro_precision": per_user_df["precision"].mean(),
        "macro_recall": per_user_df["recall"].mean(),
        "macro_map": per_user_df["map"].mean(),
        "macro_ndcg": per_user_df["ndcg"].mean(),
        "users_evaluated": total_users,
        "per_user": per_user_df,
    }

## Execução

In [7]:
data_dir = os.path.join(os.getcwd(), "data")
if not os.path.exists(data_dir):
    data_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "data"))

review_path = os.path.join(data_dir, "review_final.json")
business_path = os.path.join(data_dir, "business_final.json")

print("Loading reviews and business categories...")
user_ratings, user_item_events = load_reviews(review_path)
categories = load_business_categories(business_path)
print(f"Loaded {len(user_ratings)} users and {len(categories)} businesses.")

train_user_ratings, test_set = split_train_test_temporal(
    user_item_events,
    min_ratings=3,
    test_ratio=0.2,
    min_test_items=2,
)

item_counts, item_mean, global_mean = build_item_stats(train_user_ratings)

popularity_candidates = [item for item, _ in item_counts.most_common()]
all_items = list(item_mean.keys())
user_norms = compute_user_norms(train_user_ratings)
user_means = {
    user_id: (sum(ratings.values()) / len(ratings))
    for user_id, ratings in train_user_ratings.items()
    if ratings
}

test_relevance_by_user = build_test_relevance_by_user(test_set)
min_relevant_test = min((len(items) for items in test_relevance_by_user.values()), default=0)
avg_relevant_test = (
    sum(len(items) for items in test_relevance_by_user.values()) / len(test_relevance_by_user)
    if test_relevance_by_user
    else 0.0
)

print("Split strategy: temporal per user (oldest -> train, most recent -> test)")
print(f"Train users: {len(train_user_ratings)} | Test cases: {len(test_set)} | Candidate items: {len(all_items)}")
print(f"Relevant test items per evaluated user -> min: {min_relevant_test}, avg: {avg_relevant_test:.2f}")

K = 10

collab_cosine_cache = {}
collab_jaccard_cache = {}


def cosine_score_loader(user_id):
    if user_id not in collab_cosine_cache:
        collab_cosine_cache[user_id] = build_collaborative_score_map_cosine(
            user_id,
            train_user_ratings,
            user_norms,
        )
    return collab_cosine_cache[user_id]


def jaccard_score_loader(user_id):
    if user_id not in collab_jaccard_cache:
        collab_jaccard_cache[user_id] = build_collaborative_score_map_jaccard(
            user_id,
            train_user_ratings,
        )
    return collab_jaccard_cache[user_id]


# --------------------------
# 1) RMSE (rating prediction)
# --------------------------
baseline_rmse = evaluate_rmse(
    test_set,
    lambda user_id, item_id: predict_baseline_rating(item_id, item_mean, global_mean),
    label="Baseline RMSE",
)
content_rmse = evaluate_rmse(
    test_set,
    lambda user_id, item_id: predict_content_rating(
        user_id,
        item_id,
        train_user_ratings,
        categories,
        global_mean,
    ),
    label="Content RMSE",
)
collab_cosine_rmse = evaluate_rmse(
    test_set,
    lambda user_id, item_id: predict_from_score_loader(
        user_id,
        item_id,
        cosine_score_loader,
        user_means,
        global_mean,
    ),
    label="Collaborative Cosine RMSE",
)
collab_jaccard_rmse = evaluate_rmse(
    test_set,
    lambda user_id, item_id: predict_from_score_loader(
        user_id,
        item_id,
        jaccard_score_loader,
        user_means,
        global_mean,
    ),
    label="Collaborative Jaccard RMSE",
)

rmse_df = pd.DataFrame(
    [
        {"model": "baseline", "rmse": baseline_rmse},
        {"model": "content", "rmse": content_rmse},
        {"model": "collaborative_cosine", "rmse": collab_cosine_rmse},
        {"model": "collaborative_jaccard", "rmse": collab_jaccard_rmse},
    ]
)

# ------------------------------------------
# 2) Ranking metrics by user on test (top-K)
# ------------------------------------------
baseline_rank_eval = evaluate_ranking_metrics_by_user(
    test_set,
    lambda user_id, k: rank_baseline(user_id, train_user_ratings, popularity_candidates, item_mean, k),
    K,
    label=f"Baseline Ranking@{K}",
)
content_rank_eval = evaluate_ranking_metrics_by_user(
    test_set,
    lambda user_id, k: rank_content(user_id, train_user_ratings, categories, all_items, k),
    K,
    label=f"Content Ranking@{K}",
)
collab_cosine_rank_eval = evaluate_ranking_metrics_by_user(
    test_set,
    lambda user_id, k: rank_from_score_loader(user_id, k, cosine_score_loader),
    K,
    label=f"Collaborative Cosine Ranking@{K}",
)
collab_jaccard_rank_eval = evaluate_ranking_metrics_by_user(
    test_set,
    lambda user_id, k: rank_from_score_loader(user_id, k, jaccard_score_loader),
    K,
    label=f"Collaborative Jaccard Ranking@{K}",
)

ranking_summary_df = pd.DataFrame(
    [
        {
            "model": "baseline",
            f"precision@{K}": baseline_rank_eval["macro_precision"],
            f"recall@{K}": baseline_rank_eval["macro_recall"],
            f"map@{K}": baseline_rank_eval["macro_map"],
            f"ndcg@{K}": baseline_rank_eval["macro_ndcg"],
            "users_evaluated": baseline_rank_eval["users_evaluated"],
        },
        {
            "model": "content",
            f"precision@{K}": content_rank_eval["macro_precision"],
            f"recall@{K}": content_rank_eval["macro_recall"],
            f"map@{K}": content_rank_eval["macro_map"],
            f"ndcg@{K}": content_rank_eval["macro_ndcg"],
            "users_evaluated": content_rank_eval["users_evaluated"],
        },
        {
            "model": "collaborative_cosine",
            f"precision@{K}": collab_cosine_rank_eval["macro_precision"],
            f"recall@{K}": collab_cosine_rank_eval["macro_recall"],
            f"map@{K}": collab_cosine_rank_eval["macro_map"],
            f"ndcg@{K}": collab_cosine_rank_eval["macro_ndcg"],
            "users_evaluated": collab_cosine_rank_eval["users_evaluated"],
        },
        {
            "model": "collaborative_jaccard",
            f"precision@{K}": collab_jaccard_rank_eval["macro_precision"],
            f"recall@{K}": collab_jaccard_rank_eval["macro_recall"],
            f"map@{K}": collab_jaccard_rank_eval["macro_map"],
            f"ndcg@{K}": collab_jaccard_rank_eval["macro_ndcg"],
            "users_evaluated": collab_jaccard_rank_eval["users_evaluated"],
        },
    ]
)

# Mantemos a granularidade por utilizador para análise no relatório,
# sem gerar tabela de "maus utilizadores" no output principal.
per_user_ranking_df = pd.concat(
    [
        baseline_rank_eval["per_user"].assign(model="baseline"),
        content_rank_eval["per_user"].assign(model="content"),
        collab_cosine_rank_eval["per_user"].assign(model="collaborative_cosine"),
        collab_jaccard_rank_eval["per_user"].assign(model="collaborative_jaccard"),
    ],
    ignore_index=True,
)

print("\nRMSE summary")
display(rmse_df)

print(f"\nRanking summary (macro average by user) @ {K}")
display(ranking_summary_df)

Loading reviews and business categories...

Loaded 300 users and 18806 businesses.
Split strategy: temporal per user (oldest -> train, most recent -> test)
Train users: 300 | Test cases: 5260 | Candidate items: 15470
Relevant test items per evaluated user -> min: 2, avg: 17.59
Baseline RMSE: 10% (526/5260) - 0.0s
Baseline RMSE: 20% (1052/5260) - 0.0s
Baseline RMSE: 30% (1578/5260) - 0.0s
Baseline RMSE: 40% (2104/5260) - 0.0s
Baseline RMSE: 50% (2630/5260) - 0.0s
Baseline RMSE: 60% (3156/5260) - 0.0s
Baseline RMSE: 70% (3682/5260) - 0.0s
Baseline RMSE: 80% (4208/5260) - 0.0s
Baseline RMSE: 90% (4734/5260) - 0.0s
Baseline RMSE: 100% (5260/5260) - 0.0s
Content RMSE: 10% (526/5260) - 0.1s
Content RMSE: 20% (1052/5260) - 0.1s

Content RMSE: 30% (1578/5260) - 0.3s
Content RMSE: 40% (2104/5260) - 0.3s
Content RMSE: 50% (2630/5260) - 0.4s
Content RMSE: 60% (3156/5260) - 0.5s

Content RMSE: 70% (3682/5260) - 0.7s

Content RMSE: 80% (4208/5260) - 1.0s

Content RMSE: 90% (4734/5260) - 1.4s
Content RMSE: 100% (5260/5260) - 1.4s
Collaborative Cosine RMSE: 10% (526/5260) - 0.1s
Collaborative Cosine RMSE: 20% (1052/5260) - 0.2s

Collaborative Cosine RMSE: 30% (1578/5260) - 0.2s
Collaborative Cosine RMSE: 40% (2104/5260) - 0.3s
Collaborative Cosine RMSE: 50% (2630/5260) - 0.4s
Collaborative Cosine RMSE: 60% (3156/5260) - 0.4s
Collaborative Cosine RMSE: 70% (3682/5260) - 0.5s

Collaborative Cosine RMSE: 80% (4208/5260) - 0.5s
Collaborative Cosine RMSE: 90% (4734/5260) - 0.6s
Collaborative Cosine RMSE: 100% (5260/5260) - 0.6s
Collaborative Jaccard RMSE: 10% (526/5260) - 0.1s

Collaborative Jaccard RMSE: 20% (1052/5260) - 0.2s
Collaborative Jaccard RMSE: 30% (1578/5260) - 0.3s
Collaborative Jaccard RMSE: 40% (2104/5260) - 0.4s

Collaborative Jaccard RMSE: 50% (2630/5260) - 0.4s
Collaborative Jaccard RMSE: 60% (3156/5260) - 0.5s
Collaborative Jaccard RMSE: 70% (3682/5260) - 0.6s
Collaborative Jaccard RMSE: 80% (4208/5260) - 0.6s
Collaborative Jaccard RMSE: 90% (4734/5260) - 0.6s

Collaborative Jaccard RMSE: 100% (5260/5260) - 0.7s
Baseline Ranking@10: 10% (30/299) - 0.0s
Baseline Ranking@10: 20% (60/299) - 0.0s
Baseline Ranking@10: 30% (90/299) - 0.0s
Baseline Ranking@10: 40% (120/299) - 0.1s
Baseline Ranking@10: 50% (150/299) - 0.1s
Baseline Ranking@10: 60% (180/299) - 0.1s
Baseline Ranking@10: 70% (210/299) - 0.1s
Baseline Ranking@10: 80% (240/299) - 0.1s
Baseline Ranking@10: 90% (270/299) - 0.1s
Baseline Ranking@10: 100% (299/299) - 0.2s

Content Ranking@10: 10% (30/299) - 0.8s

Content Ranking@10: 20% (60/299) - 1.6s

Content Ranking@10: 30% (90/299) - 2.4s

Content Ranking@10: 40% (120/299) - 3.1s

Content Ranking@10: 50% (150/299) - 3.9s

Content Ranking@10: 60% (180/299) - 4.6s

Content Ranking@10: 70% (210/299) - 5.5s

Content Ranking@10: 80% (240/299) - 6.3s

Content Ranking@10: 90% (270/299) - 7.2s

Content Ranking@10: 100% (299/299) - 8.0s
Collaborative Cosine Ranking@10: 10% (30/299) - 0.0s
Collaborative Cosine Ranking@10: 20% (60/299) - 0.0s
Collaborative Cosine Ranking@10: 30% (90/299) - 0.1s
Collaborative Cosine Ranking@10: 40% (120/299) - 0.1s
Collaborative Cosine Ranking@10: 50% (150/299) - 0.1s
Collaborative Cosine Ranking@10: 60% (180/299) - 0.1s
Collaborative Cosine Ranking@10: 70% (210/299) - 0.1s
Collaborative Cosine Ranking@10: 80% (240/299) - 0.1s
Collaborative Cosine Ranking@10: 90% (270/299) - 0.1s
Collaborative Cosine Ranking@10: 100% (299/299) - 0.1s
Collaborative Jaccard Ranking@10: 10% (30/299) - 0.0s
Collaborative Jaccard Ranking@10: 20% (60/299) - 0.0s
Collaborative Jaccard Ranking@10: 30% (90/299) - 0.0s
Collaborative Jaccard Ranking@10: 40% (120/299) - 0.0s
Collaborative Jaccard Ranking@10: 50% (150/299) - 0.1s
Collaborative Jaccard Ranking@10: 60% (180/299) - 0.1s
Collaborative Jaccard Ranking@10: 70% (210/299) - 0.1s

Collaborative Jaccard Ranking@10: 80% (240/299) - 0.1s
Collaborative Jaccard Ranking@10: 90% (270/299) - 0.1s
Collaborative Jaccard Ranking@10: 100% (299/299) - 0.1s

RMSE summary

                   model      rmse
0               baseline  1.180047
1                content  1.083462
2   collaborative_cosine  1.133282
3  collaborative_jaccard  1.134046

Ranking summary (macro average by user) @ 10

,model,precision@10,recall@10,map@10,ndcg@10,users_evaluated
0,baseline,0.006020,0.002337,0.002099,0.006430,299
1,content,0.002676,0.001068,0.000806,0.002728,299
2,collaborative_cosine,0.002341,0.001559,0.000519,0.002096,299
3,collaborative_jaccard,0.003679,0.002437,0.000975,0.003594,299

## Solução híbrida (weighted) vs abordagens individuais

O sistema implantado usa um **híbrido ponderado** (weighted hybrid). Aqui
comparamos esse híbrido com cada abordagem individual nas mesmas métricas.

- **RMSE** (predição de rating): híbrido = `0.6 · colaborativo (cosseno) + 0.4 · conteúdo`.
- **Ranking@K**: híbrido = `0.6 · colaborativo_norm + 0.4 · conteúdo (Jaccard perfil↔item)`,
  com os componentes normalizados a [0,1]. A componente social do sistema
  online é omitida aqui (o grafo de amigos é esparso no split de teste).

### Cold start de itens
Itens com poucas avaliações de treino são invisíveis ao filtro colaborativo.
Medimos quantos **itens "cold"** (menos de 5 ratings de treino) cada modelo
consegue efetivamente colocar no top-K — a base empírica da estratégia de
cold start de itens (recuperação content-based).

In [8]:
# SISREC_HYBRID_BLOCK — híbrido vs individual + cold start de itens
HYBRID_W_CF = 0.6   # peso colaborativo (RMSE)
HYBRID_W_CB = 0.4   # peso conteúdo (RMSE)
RANK_W_CF = 0.6     # peso colaborativo (ranking)
RANK_W_CONTENT = 0.4  # peso conteúdo/perfil (ranking)
COLD_THRESHOLD = 5  # item 'cold' = < 5 ratings de treino


def predict_hybrid_rating(user_id, item_id):
    collab = predict_from_score_loader(
        user_id, item_id, cosine_score_loader, user_means, global_mean
    )
    content = predict_content_rating(
        user_id, item_id, train_user_ratings, categories, global_mean
    )
    return HYBRID_W_CF * collab + HYBRID_W_CB * content


def rank_hybrid(user_id, k):
    collab = cosine_score_loader(user_id)
    profile = build_user_profile_categories(user_id, train_user_ratings, categories)
    rated = set(train_user_ratings.get(user_id, {}))
    scores = []
    for item_id in all_items:
        if item_id in rated:
            continue
        collab_norm = collab.get(item_id, 0.0) / 5.0
        content_sim = jaccard_similarity(profile, categories.get(item_id, set()))
        if collab_norm == 0.0 and content_sim == 0.0:
            continue
        score = RANK_W_CF * collab_norm + RANK_W_CONTENT * content_sim
        scores.append((score, item_id))
    scores.sort(key=lambda x: x[0], reverse=True)
    return [item_id for _, item_id in scores[:k]]


# 1) RMSE do híbrido
hybrid_rmse = evaluate_rmse(test_set, predict_hybrid_rating, label='Hybrid RMSE')

# 2) Ranking do híbrido
hybrid_rank_eval = evaluate_ranking_metrics_by_user(
    test_set, lambda user_id, k: rank_hybrid(user_id, k), K,
    label=f'Hybrid Ranking@{K}',
)

# Tabelas comparativas (híbrido + individuais)
rmse_comparison_df = pd.concat(
    [rmse_df, pd.DataFrame([{'model': 'hybrid_weighted', 'rmse': hybrid_rmse}])],
    ignore_index=True,
).sort_values('rmse').reset_index(drop=True)

ranking_comparison_df = pd.concat(
    [
        ranking_summary_df,
        pd.DataFrame([{
            'model': 'hybrid_weighted',
            f'precision@{K}': hybrid_rank_eval['macro_precision'],
            f'recall@{K}': hybrid_rank_eval['macro_recall'],
            f'map@{K}': hybrid_rank_eval['macro_map'],
            f'ndcg@{K}': hybrid_rank_eval['macro_ndcg'],
            'users_evaluated': hybrid_rank_eval['users_evaluated'],
        }]),
    ],
    ignore_index=True,
).sort_values(f'ndcg@{K}', ascending=False).reset_index(drop=True)

# 3) Cold start de itens: exposição média de itens 'cold' no top-K
cold_items = {item_id for item_id in all_items if item_counts.get(item_id, 0) < COLD_THRESHOLD}
eval_users = list(test_relevance_by_user.keys())
print(f'Itens cold (<{COLD_THRESHOLD} ratings treino): {len(cold_items)} de {len(all_items)}')


def avg_cold_in_topk(ranker, k, users):
    if not users:
        return 0.0
    total = 0
    for user_id in users:
        recs = ranker(user_id, k)
        total += sum(1 for item_id in recs if item_id in cold_items)
    return total / len(users)


cold_exposure_df = pd.DataFrame([
    {'model': 'baseline', f'avg_cold_items_top{K}': avg_cold_in_topk(
        lambda u, k: rank_baseline(u, train_user_ratings, popularity_candidates, item_mean, k), K, eval_users)},
    {'model': 'collaborative_cosine', f'avg_cold_items_top{K}': avg_cold_in_topk(
        lambda u, k: rank_from_score_loader(u, k, cosine_score_loader), K, eval_users)},
    {'model': 'content', f'avg_cold_items_top{K}': avg_cold_in_topk(
        lambda u, k: rank_content(u, train_user_ratings, categories, all_items, k), K, eval_users)},
    {'model': 'hybrid_weighted', f'avg_cold_items_top{K}': avg_cold_in_topk(
        lambda u, k: rank_hybrid(u, k), K, eval_users)},
])

print('\nRMSE — híbrido vs individuais (menor é melhor)')
display(rmse_comparison_df)
print(f'\nRanking@{K} — híbrido vs individuais (maior é melhor)')
display(ranking_comparison_df)
print(f'\nCold start de itens — média de itens cold no top-{K}')
display(cold_exposure_df)

Hybrid RMSE: 10% (526/5260) - 0.1s
Hybrid RMSE: 20% (1052/5260) - 0.1s

Hybrid RMSE: 30% (1578/5260) - 0.3s
Hybrid RMSE: 40% (2104/5260) - 0.4s
Hybrid RMSE: 50% (2630/5260) - 0.4s
Hybrid RMSE: 60% (3156/5260) - 0.5s

Hybrid RMSE: 70% (3682/5260) - 0.8s

Hybrid RMSE: 80% (4208/5260) - 1.1s

Hybrid RMSE: 90% (4734/5260) - 1.7s
Hybrid RMSE: 100% (5260/5260) - 1.8s

Hybrid Ranking@10: 10% (30/299) - 1.0s

Hybrid Ranking@10: 20% (60/299) - 2.1s

Hybrid Ranking@10: 30% (90/299) - 3.0s

Hybrid Ranking@10: 40% (120/299) - 3.7s

Hybrid Ranking@10: 50% (150/299) - 4.7s

Hybrid Ranking@10: 60% (180/299) - 5.8s

Hybrid Ranking@10: 70% (210/299) - 7.0s

Hybrid Ranking@10: 80% (240/299) - 8.5s

Hybrid Ranking@10: 90% (270/299) - 9.8s

Hybrid Ranking@10: 100% (299/299) - 10.7s
Itens cold (<5 ratings treino): 15222 de 15470

RMSE — híbrido vs individuais (menor é melhor)

                   model      rmse
0        hybrid_weighted  1.076893
1                content  1.083462
2   collaborative_cosine  1.133282
3  collaborative_jaccard  1.134046
4               baseline  1.180047

Ranking@10 — híbrido vs individuais (maior é melhor)

,model,precision@10,recall@10,map@10,ndcg@10,users_evaluated
0,baseline,0.006020,0.002337,0.002099,0.006430,299
1,hybrid_weighted,0.004348,0.003026,0.001275,0.004412,299
2,collaborative_jaccard,0.003679,0.002437,0.000975,0.003594,299
3,content,0.002676,0.001068,0.000806,0.002728,299
4,collaborative_cosine,0.002341,0.001559,0.000519,0.002096,299

Cold start de itens — média de itens cold no top-10

                  model  avg_cold_items_top10
0              baseline              0.000000
1  collaborative_cosine              9.063545
2               content              9.190635
3       hybrid_weighted              9.418060